<expression> ::= <assignment> | <operation> | <call> | <literal>

<assignment> ::= <identifier> <equals> <expression> <semicolon>
<operation> ::= <expression> <operator> <expression>
<call> ::= <identifier> <brcktl> <expression> <brcktr>
<literal> ::= <number>