//noinspection BnfUnusedRuleForFile
<number> ::= "[0-9]+"

<int> ::= "int"
<brcktl> ::= "\("
<brcktr> ::= "\)"
<komma> ::= ","
<equals> ::= "(?<!=)=(?!=)"
<if> ::= "if"
<return> ::= "return"
<fun> ::= "fun"
<while> ::= "while"
<semicolon> ::= ";"
<add> ::= "\+"
<sub> ::= "-"
<exp> ::= "\^"
<div> ::= "\/"
<mult> ::= "\*"
<mod> ::= "\%"
<eqeq> ::= "\=\="
<excleq> ::= "\!\="
<and_gate> ::= "\&\&"
<or_gate> ::= "\|\|"

<identifier> ::= "[a-zA-Z][a-zA-Z0-9]*"
<type> ::= <int>
