//noinspection BnfUnusedRuleForFile
<number> ::= "[0-9]+"

<brcktl> ::= "\("
<brcktr> ::= "\)"
<komma> ::= ","
<equals> ::= "(?<!=)=(?!=)"
<if> ::= "if"
<return> ::= "return"
<fun> ::= "fun"
<while> ::= "while"
<semicolon> ::= ";"
<operator> ::= "-|\+|\^\/|\*|\%"
<eqeq> ::= "\=\="
<excleq> ::= "\!\="
<and_gate> ::= "\&\&"
<expressionLst> ::= "TODO"
<or_gate> ::= "\|\|"

<identifier> ::= "[a-zA-Z][a-zA-Z0-9]*"
