//noinspection BnfUnusedRuleForFile

<double> ::= "[0-9][0-9]{0,}(\.){0,1}[0-9]{0,}"

<curlyl> ::= "\{"
<curlyr> ::= "\}"
<brcktl> ::= "\("
<brcktr> ::= "\)"
<comma> ::= ","
<equals> ::= "(?<!=)=(?!=)"
<if> ::= "if"
<else> ::= "else"
<return> ::= "return"
<fun> ::= "fun"
<while> ::= "while"
<for> ::= "for"
<semicolon> ::= ";"
<operator> ::= "\/|\*|\%"
<plusminus> ::= "-|\+"
<comparator> ::= "\<|\>|\<\=|\>\="
<equality> ::= "\=\=|\!\="
<and_gate> ::= "\&\&"
<expressionLst> ::= "TODO"
<identifierNull> ::= "TODO"
<expressionNull> ::= "TODO"
<any> ::= "TODO"
<type> ::= "TODO"
<typeNull> ::= "TODO"
<line_comment> ::= "#"
<var> ::= "var"
<class> ::= "class"
<dot> ::= "\."
<colon> ::= "\:"
<nullValue> ::= "null"
<or> ::= "\|\|"
<and> ::= "\&\&"
<bang> ::= "\!"
<closedl> ::= "\["
<closedr> ::= "\]"

<identifier> ::= "[a-zA-Z][a-zA-Z0-9]*"